services:
  preparation:
    container_name: preparation
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: preparation
    image: preparation
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/image_server
    restart: always
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - ./cache:/app/cache
      - ./ComfyUI:/app/image_server/ComfyUI
      - ./docker/docker-compose.yaml:/app/docker-compose.yaml
      - ./docker/Dockerfile:/app/Dockerfile
