services:
  setup:
    container_name: setup
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: setup
    image: setup
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app
    restart: always
    volumes:
      - ./cache:/app/cache

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: app
    image: app
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/image_server
    restart: always
    depends_on:
      - setup
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - ./cache:/app/cache

  comfy:
    container_name: comfy
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: comfy
    image: comfy
    depends_on:
      - setup
    environment:
      PORT: ${PORT:-8188}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/image_server
    restart: always
    volumes:
      - ./cache:/app/cache
