services:
  setup:
    container_name: setup
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: setup
    image: setup
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app
    restart: always
    volumes:
      - ./cache:/app/cache
      - ./image_server:/server

  comfy:
    container_name: comfy
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: comfy
    image: comfy
    depends_on:
      - setup
    environment:
      PORT: ${PORT:-8188}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/server/ComfyUI
    restart: always
    ports:
      - 8188:8188
    volumes:
      - ./cache:/app/cache
      - ./image_server:/server
    networks:
      - image_server

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: app
    image: app
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/server
    restart: always
    depends_on:
      - setup
      - comfy
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - ./cache:/app/cache
      - ./image_server:/server
    networks:
      - image_server

networks:
  image_server:
    name: image_server
    external: true