services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app
    image: app
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/image_server
    restart: always
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - /app:/app
  comfy:
    container_name: comfy
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: comfy
    image: comfy
    environment:
      PORT: ${PORT:-8888}
      DEVICE: ${DEVICE:-0}
      VRAM_MODE: ${VRAM_MODE:--normalvram}
      WARMUP: ${WARMUP:-true}
    working_dir: /app/image_server
    restart: always
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - /app:/app
