services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: app
    image: app
    environment:
      PORT: ${PORT}
      DEVICE: ${DEVICE}
      VRAM_MODE: ${VRAM_MODE}
      WARMUP: ${WARMUP}
    working_dir: /app/image_server
    restart: always
    ports:
      - 8888:${PORT}
    volumes:
      - /app:/app
  comfy:
    container_name: comfy
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: comfy
    image: comfy
    environment:
      PORT: ${PORT}
      DEVICE: ${DEVICE}
      VRAM_MODE: ${VRAM_MODE}
      WARMUP: ${WARMUP}
    working_dir: /app/image_server
    restart: always
    ports:
      - 8888:${PORT}
    volumes:
      - /app:/app
